### ISSUE TITLE
Pebble JS compiling error

### ISSUE THREAD

**Issue by marcteys** [pebble/cloudpebble#178]
When I try to compile, I have this error

Traceback (most recent call last):
  File "/app/sdk3/bin/../pebble-tool/pebble.py", line 4, in <module>
    import pebble_tool
  File "/app/sdk3/pebble-tool/pebble_tool/__init__.py", line 10, in 
    from .commands.base import register_children
  File "/app/sdk3/pebble-tool/pebble_tool/commands/base.py", line 10, in 
    from libpebble2.communication import PebbleConnection
ImportError: No module named libpebble2.communication

**Comment by marcteys** [comment]
Seems to be back now, it was probably due to the new sdk ?
Anyway the problem is not happening anymore !

**Comment by imee12** [comment]
I am getting the same error with an import error. How did you fix it? Thanks!
 
File "/Users/imee/pebble-dev/PebbleSDK-3.3/bin/../pebble-tool/pebble.py", line 4, in <module>
    import pebble_tool
  File "/Users/imee/pebble-dev/PebbleSDK-3.3/pebble-tool/pebble_tool/__init__.py", line 8, in <module>
    import requests.packages.urllib3 as urllib3
ImportError: No module named requests.packages.urllib3

**Comment by taozhijiang** [comment]
I also have this problem. Want to study pebble development, but no official tech support.
