### ISSUE TITLE
Build breaks when a Pebblekit file is added to a Rocky.js project

### ISSUE THREAD

**Issue by thePaulV** [pebble/cloudpebble#333]
In a Rocky.js project on on beta.cloudpebble.net, adding a Pebblekit JS file to the project breaks the build.

Steps to reproduce:
1. Create a new Rocky project on cloudpebble (beta)
2. Create a watch-side rocky file, put a comment in it and save
3. Build - it succeeds
4. Create a phone-side pebblekit, put a comment in it and save
5. Build - fails

What should happen:
* Build succeeds

What happens:
* Build fails

Log:
```
Setting top to                           : /tmp/tmpk9_QTS 
Setting out to                           : /tmp/tmpk9_QTS/build 
Checking for program node,nodejs         : /app/.heroku/node/bin/node 
Found Pebble SDK for diorite in:         : /app/sdk3/pebble/diorite 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for chalk in:           : /app/sdk3/pebble/chalk 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
Found Pebble SDK for basalt in:          : /app/sdk3/pebble/basalt 
Checking for program gcc,cc              : arm-none-eabi-gcc 
Checking for program ar                  : arm-none-eabi-ar 
'configure' finished successfully (0.102s)
Waf: Entering directory `/tmp/tmpk9_QTS/build'
[ 3/59] message_key_header:  -> build/include/message_keys.auto.h
[ 2/59] message_key_definitions:  -> build/src/message_keys.auto.c
[ 3/59] message_key_json:  -> build/js/message_keys.json
[ 6/59] diorite | appinfo.auto.c:  -> build/diorite/appinfo.auto.c
[ 6/59] diorite | subst: ../../app/sdk3/pebble/common/pebble_app.ld.template -> build/diorite/pebble_app.ld.auto
[ 6/59] diorite | appinfo.json:  -> build/appinfo.json
[ 7/59] diorite | rocky.c: ../../app/sdk3/pebble/common/include/rocky.c -> build/diorite/src/rocky.c
[ 9/59] diorite | lint_js: src/rocky/index.js
[ 9/59] diorite | c: build/src/message_keys.auto.c -> build/src/message_keys.auto.c.8.o
[10/59] diorite | merge_js: src/rocky/index.js ../../app/sdk3/pebble/common/include/rocky.js -> build/resources/rocky-app.js
[11/59] diorite | reso: build/resources/rocky-app.js -> build/diorite/resources/rocky-app.js.JS_SNAPSHOT.reso
[12/59] diorite | resource_ball: build/diorite/resources/rocky-app.js.JS_SNAPSHOT.reso -> build/diorite/system_resources.resball
[13/59] diorite | generate_resource_id_header: build/diorite/system_resources.resball -> build/diorite/src/resource_ids.auto.h
[15/59] diorite | generate_pbpack: build/diorite/system_resources.resball -> build/diorite/app_resources.pbpack
[15/59] diorite | generate_resource_id_definitions: build/diorite/system_resources.resball -> build/diorite/src/resource_ids.auto.c
[16/59] diorite | c: build/diorite/src/rocky.c -> build/diorite/src/rocky.c.8.o
[18/59] diorite | c: build/diorite/appinfo.auto.c -> build/diorite/appinfo.auto.c.8.o
[18/59] diorite | c: build/diorite/src/resource_ids.auto.c -> build/diorite/src/resource_ids.auto.c.8.o
[19/59] diorite | cprogram: build/diorite/src/rocky.c.8.o build/diorite/appinfo.auto.c.8.o build/diorite/src/resource_ids.auto.c.8.o build/src/message_keys.auto.c.8.o -> build/diorite/pebble-app.elf

========== Lint Results: index.js ==========
 

Everything looks AWESOME!

 
[22/59] chalk | subst: ../../app/sdk3/pebble/common/pebble_app.ld.template -> build/chalk/pebble_app.ld.auto
[23/59] chalk | appinfo.auto.c:  -> build/chalk/appinfo.auto.c
[23/59] chalk | rocky.c: ../../app/sdk3/pebble/common/include/rocky.c -> build/chalk/src/rocky.c
[26/59] chalk | c: build/src/message_keys.auto.c -> build/src/message_keys.auto.c.16.o
[27/59] chalk | reso: build/resources/rocky-app.js -> build/chalk/resources/rocky-app.js.JS_SNAPSHOT.reso
[28/59] chalk | resource_ball: build/chalk/resources/rocky-app.js.JS_SNAPSHOT.reso -> build/chalk/system_resources.resball
[31/59] chalk | generate_pbpack: build/chalk/system_resources.resball -> build/chalk/app_resources.pbpack
[31/59] chalk | generate_resource_id_definitions: build/chalk/system_resources.resball -> build/chalk/src/resource_ids.auto.c
[31/59] chalk | generate_resource_id_header: build/chalk/system_resources.resball -> build/chalk/src/resource_ids.auto.h
[32/59] chalk | c: build/chalk/src/rocky.c -> build/chalk/src/rocky.c.16.o
[33/59] chalk | c: build/chalk/appinfo.auto.c -> build/chalk/appinfo.auto.c.16.o
[34/59] chalk | c: build/chalk/src/resource_ids.auto.c -> build/chalk/src/resource_ids.auto.c.16.o
[35/59] chalk | cprogram: build/chalk/src/rocky.c.16.o build/chalk/appinfo.auto.c.16.o build/chalk/src/resource_ids.auto.c.16.o build/src/message_keys.auto.c.16.o -> build/chalk/pebble-app.elf
[37/59] basalt | subst: ../../app/sdk3/pebble/common/pebble_app.ld.template -> build/basalt/pebble_app.ld.auto
[38/59] basalt | appinfo.auto.c:  -> build/basalt/appinfo.auto.c
[39/59] basalt | rocky.c: ../../app/sdk3/pebble/common/include/rocky.c -> build/basalt/src/rocky.c
[40/59] basalt | c: build/src/message_keys.auto.c -> build/src/message_keys.auto.c.24.o
[43/59] basalt | reso: build/resources/rocky-app.js -> build/basalt/resources/rocky-app.js.JS_SNAPSHOT.reso
[45/59] merge_js: src/pkjs/something.js build/js/message_keys.json ../../app/sdk3/pebble/common/include/safe.js ../../app/sdk3/pebble/common/include/message.js -> build/pebble-js-app.js
[45/59] diorite | pebble-app.raw.bin: build/diorite/pebble-app.elf -> build/diorite/pebble-app.raw.bin
[46/59] chalk | pebble-app.raw.bin: build/chalk/pebble-app.elf -> build/chalk/pebble-app.raw.bin
Waf: Leaving directory `/tmp/tmpk9_QTS/build'
Build failed
Traceback (most recent call last):
  File "/app/sdk3/pebble/.waf-1.7.11-f3ed116f7ca483b2fb7db4d89665f500/waflib/Task.py", line 123, in process
    ret=self.run()
  File "/app/sdk3/pebble/.waf-1.7.11-f3ed116f7ca483b2fb7db4d89665f500/waflib/Task.py", line 47, in run
    return m1(self)
  File "/app/sdk3/pebble/.waf-1.7.11-f3ed116f7ca483b2fb7db4d89665f500/waflib/extras/process_js.py", line 114, in run
    bld.fatal("\n\nJS entry file '{}' not found in JS source files '{}'. We expect to find ""a javascript file here that we will execute directly when your app launches.""\n\nIf you are an advanced user, you can supply the 'js_entry_file' ""parameter to 'pbl_bundle' in your wscript to change the default entry point."" Note that doing this will break CloudPebble compatibility.".format(js_entry_file,js_nodes))
  File "/app/sdk3/pebble/.waf-1.7.11-f3ed116f7ca483b2fb7db4d89665f500/waflib/Context.py", line 219, in fatal
    raise self.errors.ConfigurationError(msg,ex=ex)
ConfigurationError: 

JS entry file 'src/pkjs/index.js' not found in JS source files '[/tmp/tmpk9_QTS/src/pkjs/something.js, /tmp/tmpk9_QTS/build/js/message_keys.json, /app/sdk3/pebble/common/include/safe.js, /app/sdk3/pebble/common/include/message.js]'. We expect to find a javascript file here that we will execute directly when your app launches.

If you are an advanced user, you can supply the 'js_entry_file' parameter to 'pbl_bundle' in your wscript to change the default entry point. Note that doing this will break CloudPebble compatibility.
```

**Comment by Katharine** [comment]
This is caused by CloudPebble naming the file app.js, which is wrong — rename it to index.js and it'll work. 

(We will, of course, fix the default.)

**Comment by thePaulV** [comment]
The filename doesn't seem to matter. I just tried in a fresh project project adding a pebblekit file called "kit.js" and it results in failed builds. Renaming it to other things doesn't help, but deleting it does.

**Comment by Katharine** [comment]
The name must be index.js. kit.js is not index.js.

**Comment by thePaulV** [comment]
Thanks @Katharine, as you say that does fix it. I guess I had pebble.js on the brain with the app.js. Close as PEBCAC? :)
